openapi: "3.0.0"
info:
  title: "Bee Travels Payment Service "
  version: "1.0.0"
  description: "Basic responder Bee Travels Payment stub"
  license:
    name: "Apache 2.0"
    url: "https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE"
