language: node_js

sudo: false

node_js:
  - 10

install:
  - cd src/destination && npm install && cd ../..
  - cd src/ui && npm install && cd ../..


script:
  - cd src/destination && ./node_modules/.bin/eslint src/
