language: node_js

sudo: false

node_js:
  - 9
  - 10

stages:
  - "lint"
  - "test"

jobs:
  include:
    - stage: "lint"
      node_js: 9
      name: "Destination ES Linting"
      script: cd src/destination && npm install && ./node_modules/.bin/eslint src/
    - stage: "lint"
      node_js: 9
      name: "UI client ES Linting"
      script:
        - cd src/ui && npm install && cd ../..
        - cd src/ui/client && npm install && ./node_modules/.bin/eslint src/
    - stage: "test"
      node_js: 9
      name: "NPM testing"
      script: cd src/destination && npm install && npm test
    - stage: "lint"
      node_js: 10
      name: "Destination ES Linting"
      script: cd src/destination && npm install && ./node_modules/.bin/eslint src/
    - stage: "lint"
      node_js: 10
      name: "UI client ES Linting"
      script:
        - cd src/ui && npm install && cd ../..
        - cd src/ui/client && npm install && ./node_modules/.bin/eslint src/
    - stage: "test"
      node_js: 10
      name: "NPM testing"
      script: cd src/destination && npm install && npm test
