language: node_js

node_js:
  - 12

services:
  - docker

jobs:
  include:
    - stage: linting
      name: Destination ES Linting
      script: yarn workspace destination lint

    - name: Hotel Service ES Linting
      script: yarn workspace hotel lint

    - name: UI client ES Linting
      script:
        - yarn workspace ui-backend lint
        - yarn workspace ui-frontend lint

    - stage: testing
      name: Destination Unit Test
      script: yarn workspace destination test

    - name: Currencyexchange Unit Test
      script: yarn workspace currency-exchange test

    - stage: deploy
      name: Docker image build
      script: skip
      deploy:
      - provider: script
        script: .travis/build-and-push.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(development|v1|v2|v3)$
