language: node_js

node_js:
  - 12

services:
  - docker

jobs:
  include:
    - stage: lint
      name: Lint
      script: yarn lint

    - stage: test
      name: Destination
      script: yarn workspace destination test

    - name: Currency Exchange
      script: yarn workspace currency-exchange test

    - stage: deploy
      name: Docker image build
      script: skip
      deploy:
      - provider: script
        script: .travis/build-and-push.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(development|v1|v2|v3)$
