yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "carbon-components-react@*":
    dependencies:
      "prop-types": ">=15"
  "@carbon/icons-react@*":
    dependencies:
      "prop-types": ">=15"
    peerDependencies:
      "react": "*"

