packageExtensions:
  jss-plugin-rule-value-function@*:
    dependencies:
      tiny-warning: "*"
  parcel-bundler@*:
    dependencies:
      babel-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "@yarnpkg/plugin-constraints"

preferInteractive: true

yarnPath: .yarn/releases/yarn-berry.js
