packageExtensions:
  jss-plugin-rule-value-function@*:
    dependencies:
      tiny-warning: "*"
  parcel-bundler@*:
    dependencies:
      babel-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js
