---
version: '3.3'

services:
  base:
    image: bee-travels/node-base:v1
    build: .

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

  ui:
    build: services/ui
    ports:
      - "9000:9000"
    depends_on:
      - base
      - destination
      - hotel
      - car-rental
      - currency-exchange
    environment:
      - NODE_ENV=production
      - DESTINATION_URL=http://destination:9001
      - HOTEL_URL=http://hotel:9101
      - CAR_URL=http://car-rental:9102
      - CURRENCY_EXCHANGE_URL=http://currency-exchange:9201

  destination:
    build: services/destination-v1
    ports:
      - "9001:9001"
    depends_on:
      - base

  hotel:
      build: services/hotel-v1
      ports:
        - "9101:9101"
      depends_on:
        - base

  car-rental:
      build: services/car-rental-v1
      ports:
        - "9102:9102"
      depends_on:
        - base

  currency-exchange:
    build: services/currency-exchange
    ports:
      - "9201:9201"
    depends_on:
      - base
