---
version: '3.3'

services:
  base:
    image: bee-travels/node-base:v1
    build: .

  ui:
    build: services/ui
    ports:
      - "9000:9000"
    depends_on:
      - base
      - destination
      - hotel
      - car-rental
      - currency-exchange
      - payment

    environment:
      - DESTINATION_URL=http://destination:9001
      - HOTEL_URL=http://hotel:9101
      - CAR_URL=http://car-rental:9102
      - CURRENCY_EXCHANGE_URL=http://currency-exchange:9201
      - PAYMENT_URL=http://payment:9403

  destination:
    build: services/destination-v2
    ports:
      - "9001:9001"
    depends_on:
      - base
    environment:
        - DESTINATION_DATABASE=${DESTINATION_DATABASE}
        - MONGO_CONNECTION_URL=mongodb://localhost:27017

  hotel:
      build: services/hotel-v2
      ports:
        - "9101:9101"
      depends_on:
        - base
      environment:
        - HOTEL_DATABASE=${HOTEL_DATABASE}
        - MONGO_CONNECTION_URL=mongodb://localhost:27017

  car-rental:
      build: services/car-rental-v2
      ports:
        - "9102:9102"
      depends_on:
        - base
      environment:
        - CAR_DATABASE=${CAR_DATABASE}
        - MONGO_CONNECTION_URL=mongodb://localhost:27017

  currency-exchange:
    build: services/currency-exchange
    ports:
      - "9201:9201"
    depends_on:
      - base

  payment:
      build: services/payment-v2
      ports:
        - "9403:9403"
      depends_on:
        - base
