---
version: '3.3'

services:
  base:
    image: bee-travels/node-base:v1
    build: .

  ui:
    build: services/ui
    ports:
      - "9000:9000"
    depends_on:
      - base
      - destination
      - hotel
      - car-rental
      - currency-exchange
      - payment

    environment:
      - DESTINATION_URL=http://destination:9001
      - HOTEL_URL=http://hotel:9101
      - CAR_URL=http://car-rental:9102
      - CURRENCY_EXCHANGE_URL=http://currency-exchange:9201
      - PAYMENT_URL=http://payment:9403

  destination:
    build: services/destination-v2
    ports:
      - "9001:9001"
    depends_on:
      - base
    environment:
        - DESTINATION_DATABASE=${DESTINATION_DATABASE}
        - DESTINATION_MONGO_CONNECTION_URL=mongodb://mongo:27017
        - DESTINATION_COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
        - DESTINATION_PG_HOST=postgres
        - DESTINATION_PG_USER=postgres
        - DESTINATION_PG_PASSWORD=admin

  hotel:
      build: services/hotel-v2
      ports:
        - "9101:9101"
      depends_on:
        - base
      environment:
        - HOTEL_DATABASE=${HOTEL_DATABASE}
        - HOTEL_MONGO_CONNECTION_URL=mongodb://mongo:27017
        - HOTEL_COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
        - HOTEL_PG_HOST=postgres
        - HOTEL_PG_USER=postgres
        - HOTEL_PG_PASSWORD=admin

  car-rental:
      build: services/car-rental-v2
      ports:
        - "9102:9102"
      depends_on:
        - base
      environment:
        - CAR_DATABASE=${CAR_DATABASE}
        - CAR_MONGO_CONNECTION_URL=mongodb://mongo:27017
        - CAR_COUCH_CLOUDANT_CONNECTION_URL=http://admin:admin@couch:5984
        - CAR_PG_HOST=postgres
        - CAR_PG_USER=postgres
        - CAR_PG_PASSWORD=admin

  currency-exchange:
    build: services/currency-exchange
    ports:
      - "9201:9201"
    depends_on:
      - base

  payment:
      build: services/payment-v2
      ports:
        - "9403:9403"
      depends_on:
        - base

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
    image: mongo
    restart: always

  couch:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
