env:
  node: true
  browser: true
  es6: true
  commonjs: true
parser: "babel-eslint"
extends: 
  - "eslint:recommended"
  - "plugin:react/recommended"
parserOptions:
  ecmaVersion: 2015
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
