openapi: 3.0.3
info:
  title: Bee Travels Email V2 Service
  version: 1.0.0
  description: Email service for bee-travels application. Responsible for sending notification email to users.
  license:
    name: Apache 2.0
    url: https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE
