openapi: "3.0.0"
info:
  title: "Bee Travels Hotel V2 Service"
  version: "1.0.0"
  description: "This is a microservice that handles hotel data for Bee Travels"
  license:
    name: "Apache 2.0"
    url: "https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE"
