openapi: 3.0.3
info:
  title: Bee Travels Checkout V2 Service
  version: 1.0.0
  description: Operations associated with the payment processing flow
  license:
    name: Apache 2.0
    url: https://github.com/bee-travels/bee-travels-node/blob/master/LICENSE
